-- MySQL Script generated by MySQL Workbench
-- 01/24/16 10:22:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema huecas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema huecas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `huecas` DEFAULT CHARACTER SET utf32 ;
USE `huecas` ;

-- -----------------------------------------------------
-- Table `huecas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huecas`.`categoria` (
  `cat_id` INT NOT NULL,
  `cat_nombre` VARCHAR(60) NULL,
  `cat_descripcion` VARCHAR(60) NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huecas`.`hueca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huecas`.`hueca` (
  `hue_id` INT NOT NULL,
  `hue_nombre` VARCHAR(45) NULL,
  `hue_direccion` VARCHAR(45) NULL,
  `hue_horario` VARCHAR(45) NULL,
  `hue_logo` VARCHAR(80) NULL,
  `hue_banner` VARCHAR(80) NULL,
  `hue_menu` VARCHAR(80) NULL,
  `hue_abre` TIME(6) NULL,
  `hue_cierra` TIME(6) NULL,
  `cat_id` INT NOT NULL,
  PRIMARY KEY (`hue_id`),
  INDEX `fk_hueca_categoria_idx` (`cat_id` ASC),
  CONSTRAINT `fk_hueca_categoria`
    FOREIGN KEY (`cat_id`)
    REFERENCES `huecas`.`categoria` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huecas`.`plato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huecas`.`plato` (
  `pla_id` INT NOT NULL,
  `pla_nombre` VARCHAR(45) NULL,
  `pla_precio` DECIMAL(2) NULL,
  `pla_foto` VARCHAR(80) NULL,
  `hue_id` INT NOT NULL,
  PRIMARY KEY (`pla_id`, `hue_id`),
  INDEX `fk_plato_hueca1_idx` (`hue_id` ASC),
  CONSTRAINT `fk_plato_hueca1`
    FOREIGN KEY (`hue_id`)
    REFERENCES `huecas`.`hueca` (`hue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huecas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huecas`.`cliente` (
  `cli_cedula` VARCHAR(13) NOT NULL,
  `cli_nombre` VARCHAR(45) NULL,
  `cli_apellido` VARCHAR(45) NULL,
  `cli_direccion` VARCHAR(90) NULL,
  `cli_telefono` VARCHAR(45) NULL,
  `cli_correo` VARCHAR(80) NULL,
  PRIMARY KEY (`cli_cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huecas`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huecas`.`pedido` (
  `ped_id` INT NOT NULL,
  `ped_preciot` DECIMAL NULL,
  `ped_subt` DECIMAL NULL,
  `ped_fecha` DATE NULL,
  `cli_cedula` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`ped_id`, `cli_cedula`),
  INDEX `fk_pedido_cliente1_idx` (`cli_cedula` ASC),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`cli_cedula`)
    REFERENCES `huecas`.`cliente` (`cli_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huecas`.`galeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huecas`.`galeria` (
  `gal_id` INT NOT NULL,
  `gal_foto` VARCHAR(80) NULL,
  `gal_tipo` VARCHAR(45) NULL,
  `hue_id` INT NOT NULL,
  PRIMARY KEY (`gal_id`, `hue_id`),
  INDEX `fk_galeria_hueca1_idx` (`hue_id` ASC),
  CONSTRAINT `fk_galeria_hueca1`
    FOREIGN KEY (`hue_id`)
    REFERENCES `huecas`.`hueca` (`hue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huecas`.`detallepedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `huecas`.`detallepedido` (
  `pla_id` INT NOT NULL,
  `ped_id` INT NOT NULL,
  `det_cantidad` INT NOT NULL,
  PRIMARY KEY (`pla_id`, `ped_id`),
  INDEX `fk_plato_has_pedido_pedido1_idx` (`ped_id` ASC),
  INDEX `fk_plato_has_pedido_plato1_idx` (`pla_id` ASC),
  CONSTRAINT `fk_plato_has_pedido_plato1`
    FOREIGN KEY (`pla_id`)
    REFERENCES `huecas`.`plato` (`pla_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plato_has_pedido_pedido1`
    FOREIGN KEY (`ped_id`)
    REFERENCES `huecas`.`pedido` (`ped_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
