
			
			</div>

<script type="text/javascript" src="./js/script.js"></script>
<div id="carro" class="col-md-2">
   <div class="container-fluid" id="contienecarrito">
			<div  class="center text-center">
				<div id="carrito" style="background:rgb(200,200,200);color:black;">
					Carrito
				</div>
					<a href='php/destruir.php'><button class="btn">Vaciar carrito</button></a>
					<a href='confirmar.php'><button class="btn">Confirmar pedido</button></a>
				</div>
				   
  </div>

</div>


<footer class="col-sm-12 col-md-12 col-xs-12">
				<h6>(c) Universidad Tecnica de  Machala -12 ava Promoción - Ingenieria de Sistemas</h6>
			</footer>



		



</div>
	
</body>
</html>
